### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [mrzmmr/remark-extract-frontmatter#5]
Hi!

remark is switching to a new parser (and compiler) internally ([micromark](https://github.com/micromark/micromark), [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)), which will break this plugin.

It seems the code now integrates with the parser, but could just as well be in a transformer btw?

**Comment by mrzmmr** [comment]
Your right! I don't think it needs to integrate with the parser and can just be a transformer. I'll look into it further.

**Comment by ilyaigpetrov** [comment]
I just want to inform you that `remark@13` was released 10 days ago in case you've missed it.
This plugin will be very appreciated.

**Comment by mrzmmr** [comment]
Sorry been busy, just pushed 3.0.0 working with remark@13
